#test exception 0
int main()
{
	return main();
}
